# 2962 is the app # for the Splunk Add-On Builder

version: '3.7'

volumes:
  splunk-etc:
  splunk-var:

services:
  splunk:
    image: splunk/splunk:8.1
    hostname: splunk
    volumes:
      - splunk-etc:/opt/splunk/etc
      - splunk-var:/opt/splunk/var
      - ./splunk-licenses/splunk.lic:/splunk.lic
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=password
      - SPLUNK_LICENSE_URI=/splunk.lic
      - SPLUNK_APPS_URL=https://splunkbase.splunk.com/app/2962/release/3.0.1/download
      - SPLUNKBASE_USERNAME=${SPLUNKBASE_USERNAME}
      - SPLUNKBASE_PASSWORD=${SPLUNKBASE_PASSWORD}
    ports:
      - 127.0.0.1:8000:8000
      - 127.0.0.1:8089:8089